name: SmoothieInstaller

on:
  push:
    branches: [ "*" ]


jobs:
  release-win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022]
    
    steps:      
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8.1'
    - run: dotnet publish "src/SmoothieInstaller.csproj"

    - uses: actions/upload-artifact@v4
      with:
        name: smoothie-rs-bin-windows
        path: ./src/obj/Release/SmoothieInstaller.exe

    - name: Generate release tag
      id: tag
      run: echo "::set-output name=release_tag::Nightly_$(date +"%Y.%m.%d_%H-%M")"

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        fail_on_unmatched_files: true
        files: |
          ./src/obj/Release/SmoothieInstaller.exe
